import {
  Hospital,
  Department,
  Doctor,
  User,
  Appointment,
  Notification,
  AuditLog,
} from '../types';

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-1',
    name: 'MEDFLOW General Hospital - Central',
    code: 'MGH-C',
    tagline: 'Leading Academic & Tertiary Care Medical Center',
    address: '450 Healthcare Boulevard, Suite 100',
    city: 'Metro City',
    phone: '+1 (555) 234-5678',
    email: 'central@medflow-health.org',
    active: true,
    departments: ['dept-1', 'dept-2', 'dept-3', 'dept-4', 'dept-5', 'dept-6', 'dept-7', 'dept-8'],
  },
  {
    id: 'hosp-2',
    name: 'MEDFLOW Memorial Specialty Clinic',
    code: 'MMSC',
    tagline: 'Specialized Outpatient Surgical & Cardiac Care',
    address: '88 Riverfront Park Drive',
    city: 'Riverdale',
    phone: '+1 (555) 890-1234',
    email: 'memorial@medflow-health.org',
    active: true,
    departments: ['dept-1', 'dept-3', 'dept-6'],
  },
  {
    id: 'hosp-3',
    name: 'St. Jude Integrated Medical Center',
    code: 'SJMC',
    tagline: 'Community Focused Outpatient Care & Pediatrics',
    address: '1024 Valley View Avenue',
    city: 'Oakridge',
    phone: '+1 (555) 456-7890',
    email: 'stjude@medflow-health.org',
    active: true,
    departments: ['dept-4', 'dept-5', 'dept-6'],
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    hospitalId: 'hosp-1',
    name: 'Cardiology',
    code: 'CARD',
    icon: 'Heart',
    description: 'Comprehensive cardiovascular diagnosis, intervention, and preventive care.',
    floor: '2nd Floor - Wing A',
    roomNumbers: ['101', '102', '103'],
  },
  {
    id: 'dept-2',
    hospitalId: 'hosp-1',
    name: 'Neurology',
    code: 'NEUR',
    icon: 'Brain',
    description: 'Advanced neurological disorders, neurophysiology, and cognitive health.',
    floor: '3rd Floor - Wing B',
    roomNumbers: ['201', '202'],
  },
  {
    id: 'dept-3',
    hospitalId: 'hosp-1',
    name: 'Orthopedics',
    code: 'ORTH',
    icon: 'Bone',
    description: 'Musculoskeletal care, joint reconstruction, sports medicine, and spine clinic.',
    floor: '1st Floor - Wing C',
    roomNumbers: ['110', '111', '112'],
  },
  {
    id: 'dept-4',
    hospitalId: 'hosp-1',
    name: 'Pediatrics',
    code: 'PED',
    icon: 'Baby',
    description: 'Child wellness, pediatric developmental milestones, and acute illnesses.',
    floor: '2nd Floor - Wing D',
    roomNumbers: ['105', '106'],
  },
  {
    id: 'dept-5',
    hospitalId: 'hosp-1',
    name: 'Dermatology',
    code: 'DERM',
    icon: 'Sparkles',
    description: 'Clinical dermatology, skin oncology screenings, and phototherapy.',
    floor: '4th Floor - Wing A',
    roomNumbers: ['301', '302'],
  },
  {
    id: 'dept-6',
    hospitalId: 'hosp-1',
    name: 'General Medicine',
    code: 'GEN',
    icon: 'Stethoscope',
    description: 'Primary care, chronic disease management, and OPD consultations.',
    floor: 'Ground Floor - Main OPD',
    roomNumbers: ['001', '002', '003', '004'],
  },
  {
    id: 'dept-7',
    hospitalId: 'hosp-1',
    name: 'ENT (Otolaryngology)',
    code: 'ENT',
    icon: 'Ear',
    description: 'Ear, nose, throat, head and neck clinical evaluation.',
    floor: '3rd Floor - Wing A',
    roomNumbers: ['210', '211'],
  },
  {
    id: 'dept-8',
    hospitalId: 'hosp-1',
    name: 'Oncology',
    code: 'ONC',
    icon: 'Activity',
    description: 'Medical oncology consultations, immunotherapy, and cancer surveillance.',
    floor: '4th Floor - Wing C',
    roomNumbers: ['401', '402'],
  },
];

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    name: 'Dr. Priya Sharma, MD, FACC',
    title: 'Senior Interventional Cardiologist',
    qualifications: 'MD (Cardiology - Johns Hopkins), Fellow of ACC',
    specialization: 'Cardiology, Hypertension & Heart Failure',
    roomNumber: '101',
    consultationFee: 120,
    avgConsultationMinutes: 15,
    experienceYears: 16,
    rating: 4.9,
    currentDelayMinutes: 0,
    status: 'IN_CONSULTATION',
    schedule: {
      workingDays: [1, 2, 3, 4, 5],
      startTime: '09:00',
      endTime: '17:00',
      breakStart: '13:00',
      breakEnd: '14:00',
      slotDurationMinutes: 15,
      maxDailyAppointments: 24,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-2',
    hospitalId: 'hosp-1',
    departmentId: 'dept-1',
    name: 'Dr. Marcus Vance, MD',
    title: 'Electrophysiologist & Cardiologist',
    qualifications: 'MD (Harvard Medical), Cardiac Arrhythmia Specialist',
    specialization: 'Arrhythmias, Pacemaker Clinic & ECG',
    roomNumber: '102',
    consultationFee: 130,
    avgConsultationMinutes: 20,
    experienceYears: 12,
    rating: 4.8,
    currentDelayMinutes: 15,
    status: 'DELAYED',
    schedule: {
      workingDays: [1, 2, 3, 4, 5],
      startTime: '09:00',
      endTime: '16:30',
      breakStart: '12:30',
      breakEnd: '13:30',
      slotDurationMinutes: 20,
      maxDailyAppointments: 18,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-3',
    hospitalId: 'hosp-1',
    departmentId: 'dept-2',
    name: 'Dr. Aris Thorne, MD, PhD',
    title: 'Chief of Neurology',
    qualifications: 'MD, PhD (Stanford), Board Certified Neurologist',
    specialization: 'Stroke, Epilepsy, Migraines & Neurogenetics',
    roomNumber: '201',
    consultationFee: 150,
    avgConsultationMinutes: 20,
    experienceYears: 20,
    rating: 4.95,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 2, 3, 4],
      startTime: '09:30',
      endTime: '16:30',
      breakStart: '13:00',
      breakEnd: '14:00',
      slotDurationMinutes: 20,
      maxDailyAppointments: 16,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-4',
    hospitalId: 'hosp-1',
    departmentId: 'dept-3',
    name: 'Dr. Elena Rostova, MD',
    title: 'Consultant Orthopedic Surgeon',
    qualifications: 'MS (Orthopedics), Joint Replacement Fellowship (Mayo Clinic)',
    specialization: 'Knee & Hip Arthroplasty, Sports Injuries',
    roomNumber: '110',
    consultationFee: 110,
    avgConsultationMinutes: 15,
    experienceYears: 14,
    rating: 4.85,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 2, 3, 4, 5, 6],
      startTime: '08:30',
      endTime: '15:30',
      breakStart: '12:00',
      breakEnd: '13:00',
      slotDurationMinutes: 15,
      maxDailyAppointments: 22,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1594824813589-9a2c3dbf9411?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-5',
    hospitalId: 'hosp-1',
    departmentId: 'dept-4',
    name: 'Dr. David Cho, MD, FAAP',
    title: 'Pediatric Specialist',
    qualifications: 'MD (Columbia), Fellow of American Academy of Pediatrics',
    specialization: 'Neonatal & Child Health, Asthma, Vaccinations',
    roomNumber: '105',
    consultationFee: 90,
    avgConsultationMinutes: 15,
    experienceYears: 9,
    rating: 4.9,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 2, 3, 4, 5],
      startTime: '09:00',
      endTime: '17:00',
      breakStart: '12:30',
      breakEnd: '13:30',
      slotDurationMinutes: 15,
      maxDailyAppointments: 24,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-6',
    hospitalId: 'hosp-1',
    departmentId: 'dept-5',
    name: 'Dr. Camille Laurent, MD',
    title: 'Consultant Dermatologist',
    qualifications: 'MD (McGill), American Academy of Dermatology',
    specialization: 'Psoriasis, Eczema, Acne & Mole Screening',
    roomNumber: '301',
    consultationFee: 100,
    avgConsultationMinutes: 15,
    experienceYears: 11,
    rating: 4.75,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 2, 3, 4, 5],
      startTime: '10:00',
      endTime: '18:00',
      breakStart: '13:30',
      breakEnd: '14:30',
      slotDurationMinutes: 15,
      maxDailyAppointments: 24,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-7',
    hospitalId: 'hosp-1',
    departmentId: 'dept-6',
    name: 'Dr. Rajiv Menon, MBBS, MD',
    title: 'Senior Physician & Diabetologist',
    qualifications: 'MD (Internal Medicine), Certified Diabetologist',
    specialization: 'Diabetes, Metabolic Disorders, General OPD',
    roomNumber: '001',
    consultationFee: 80,
    avgConsultationMinutes: 15,
    experienceYears: 18,
    rating: 4.88,
    currentDelayMinutes: 0,
    status: 'IN_CONSULTATION',
    schedule: {
      workingDays: [1, 2, 3, 4, 5, 6],
      startTime: '08:30',
      endTime: '16:30',
      breakStart: '12:30',
      breakEnd: '13:30',
      slotDurationMinutes: 15,
      maxDailyAppointments: 26,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-8',
    hospitalId: 'hosp-1',
    departmentId: 'dept-6',
    name: 'Dr. Sarah Al-Mansoor, MD',
    title: 'General Internist',
    qualifications: 'MD (Internal Medicine - Oxford University)',
    specialization: 'Infectious Disease, Preventive Health, OPD Triage',
    roomNumber: '002',
    consultationFee: 75,
    avgConsultationMinutes: 15,
    experienceYears: 8,
    rating: 4.8,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 2, 3, 4, 5],
      startTime: '09:00',
      endTime: '17:00',
      breakStart: '13:00',
      breakEnd: '14:00',
      slotDurationMinutes: 15,
      maxDailyAppointments: 24,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1594824813589-9a2c3dbf9411?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-9',
    hospitalId: 'hosp-1',
    departmentId: 'dept-7',
    name: 'Dr. Kenneth Clark, MD',
    title: 'ENT & Head/Neck Surgeon',
    qualifications: 'MD, FACS, Board Certified Otolaryngologist',
    specialization: 'Sinus Surgery, Hearing Loss, Tinnitus & Vertigo',
    roomNumber: '210',
    consultationFee: 95,
    avgConsultationMinutes: 15,
    experienceYears: 15,
    rating: 4.7,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [1, 3, 5],
      startTime: '09:00',
      endTime: '15:00',
      breakStart: '12:00',
      breakEnd: '13:00',
      slotDurationMinutes: 15,
      maxDailyAppointments: 18,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'doc-10',
    hospitalId: 'hosp-1',
    departmentId: 'dept-8',
    name: 'Dr. Fatima Noor, MD',
    title: 'Medical Oncologist',
    qualifications: 'MD (Oncology - Memorial Sloan Kettering)',
    specialization: 'Solid Tumors, Chemotherapy & Immunotherapy',
    roomNumber: '401',
    consultationFee: 160,
    avgConsultationMinutes: 30,
    experienceYears: 17,
    rating: 4.96,
    currentDelayMinutes: 0,
    status: 'AVAILABLE',
    schedule: {
      workingDays: [2, 4, 5],
      startTime: '10:00',
      endTime: '16:00',
      breakStart: '13:00',
      breakEnd: '14:00',
      slotDurationMinutes: 30,
      maxDailyAppointments: 10,
    },
    leaves: [],
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256',
  },
];

export const DEMO_USERS: Record<string, User> = {
  PATIENT: {
    id: 'usr-patient-1',
    name: 'Alex Morgan',
    email: 'alex.morgan@example.com',
    phone: '+1 (555) 742-9988',
    role: 'PATIENT',
    hospitalId: 'hosp-1',
    patientId: 'pat-1',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  DOCTOR: {
    id: 'usr-doctor-1',
    name: 'Dr. Priya Sharma',
    email: 'priya.sharma@medflow-health.org',
    phone: '+1 (555) 234-1101',
    role: 'DOCTOR',
    hospitalId: 'hosp-1',
    doctorId: 'doc-1',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=256',
  },
  RECEPTIONIST: {
    id: 'usr-reception-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@medflow-health.org',
    phone: '+1 (555) 234-1102',
    role: 'RECEPTIONIST',
    hospitalId: 'hosp-1',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
  },
  HOSPITAL_ADMIN: {
    id: 'usr-admin-1',
    name: 'David Vance, MHA',
    email: 'david.vance@medflow-health.org',
    phone: '+1 (555) 234-1103',
    role: 'HOSPITAL_ADMIN',
    hospitalId: 'hosp-1',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
  },
  SUPER_ADMIN: {
    id: 'usr-super-1',
    name: 'Dr. Elena Rostova',
    email: 'superadmin@medflow-global.com',
    phone: '+1 (555) 999-0001',
    role: 'SUPER_ADMIN',
    hospitalId: 'hosp-1',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=256',
  },
};

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-patient-1',
    title: 'Appointment Confirmed',
    message: 'Your Cardiology consultation with Dr. Priya Sharma is confirmed for today at 10:30 AM. Token: C-024.',
    channel: 'IN_APP',
    type: 'BOOKING',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    read: false,
  },
  {
    id: 'notif-2',
    userId: 'usr-patient-1',
    title: 'OPD Queue Alert: 3 Patients Ahead',
    message: 'Please proceed to 2nd Floor, Wing A, Room 101. Estimated waiting time is 22 minutes.',
    channel: 'SMS',
    type: 'QUEUE_ALERT',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    read: false,
  },
  {
    id: 'notif-3',
    userId: 'usr-doctor-1',
    title: 'Daily OPD Roster Ready',
    message: '22 appointments scheduled for today across Cardiology OPD Room 101.',
    channel: 'IN_APP',
    type: 'REMINDER',
    timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    read: true,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    hospitalId: 'hosp-1',
    actorId: 'usr-reception-1',
    actorName: 'Sarah Jenkins',
    actorRole: 'RECEPTIONIST',
    action: 'CHECK_IN_PATIENT',
    resource: 'APPOINTMENT',
    resourceId: 'apt-today-2',
    oldValue: 'CONFIRMED',
    newValue: 'CHECKED_IN',
    details: 'Patient Alex Morgan checked in at OPD Central Desk. Token C-024 assigned.',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    ipAddress: '192.168.1.104',
  },
  {
    id: 'audit-2',
    hospitalId: 'hosp-1',
    actorId: 'usr-doctor-1',
    actorName: 'Dr. Priya Sharma',
    actorRole: 'DOCTOR',
    action: 'START_CONSULTATION',
    resource: 'APPOINTMENT',
    resourceId: 'apt-today-1',
    oldValue: 'WAITING',
    newValue: 'IN_CONSULTATION',
    details: 'Started consultation for Token C-023 (Patient: Robert Martinez).',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    ipAddress: '192.168.1.112',
  },
  {
    id: 'audit-3',
    hospitalId: 'hosp-1',
    actorId: 'usr-doctor-2',
    actorName: 'Dr. Marcus Vance',
    actorRole: 'DOCTOR',
    action: 'UPDATE_DOCTOR_DELAY',
    resource: 'DOCTOR',
    resourceId: 'doc-2',
    oldValue: '0 min',
    newValue: '15 min',
    details: 'Doctor marked 15 min delay due to urgent cardiac catheterization review.',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    ipAddress: '192.168.1.115',
  },
  {
    id: 'audit-4',
    hospitalId: 'hosp-1',
    actorId: 'usr-patient-1',
    actorName: 'Alex Morgan',
    actorRole: 'PATIENT',
    action: 'CREATE_APPOINTMENT',
    resource: 'APPOINTMENT',
    resourceId: 'apt-today-2',
    details: 'Patient booked online appointment via Web Portal with Cardiology Department.',
    timestamp: new Date(Date.now() - 3600000 * 5).toISOString(),
    ipAddress: '24.120.45.19',
  },
];

// Helper to generate appointments for today, yesterday, and future
export function generateSeedAppointments(): Appointment[] {
  const todayStr = new Date().toISOString().split('T')[0];
  const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  const tomorrowStr = new Date(Date.now() + 86400000).toISOString().split('T')[0];
  const inTwoDaysStr = new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0];

  const appointments: Appointment[] = [
    // Today's appointments for Dr. Priya Sharma (Cardiology)
    {
      id: 'apt-today-1',
      hospitalId: 'hosp-1',
      patientId: 'pat-99',
      patientName: 'Robert Martinez',
      patientPhone: '+1 (555) 901-2233',
      patientAge: 58,
      patientGender: 'MALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '10:00',
      endTime: '10:15',
      status: 'IN_CONSULTATION',
      reason: 'Post-angioplasty routine evaluation and lipid panel review',
      tokenNumber: 'C-023',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 12,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      checkedInAt: `${todayStr}T09:45:00Z`,
      consultationStartedAt: new Date(Date.now() - 10 * 60000).toISOString(),
      createdAt: `${todayStr}T08:00:00Z`,
      updatedAt: `${todayStr}T10:00:00Z`,
      meetLink: 'https://meet.google.com/med-flow-card',
    },
    {
      id: 'apt-today-2',
      hospitalId: 'hosp-1',
      patientId: 'pat-1', // Alex Morgan (our demo patient)
      patientName: 'Alex Morgan',
      patientPhone: '+1 (555) 742-9988',
      patientAge: 34,
      patientGender: 'FEMALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '10:15',
      endTime: '10:30',
      status: 'WAITING',
      reason: 'Occasional chest palpitations and family history of early coronary disease',
      tokenNumber: 'C-024',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 18,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 12,
      checkedInAt: `${todayStr}T09:55:00Z`,
      createdAt: `${todayStr}T08:15:00Z`,
      updatedAt: `${todayStr}T09:55:00Z`,
      meetLink: 'https://meet.google.com/med-flow-card',
    },
    {
      id: 'apt-today-3',
      hospitalId: 'hosp-1',
      patientId: 'pat-102',
      patientName: 'Michael Chang',
      patientPhone: '+1 (555) 432-8765',
      patientAge: 47,
      patientGender: 'MALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '10:30',
      endTime: '10:45',
      status: 'CHECKED_IN',
      reason: 'Hypertension follow-up and beta-blocker titration',
      tokenNumber: 'C-025',
      priority: 'FOLLOW_UP',
      bookingSource: 'ONLINE',
      noShowRiskScore: 24,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 27,
      checkedInAt: `${todayStr}T10:05:00Z`,
      createdAt: `${todayStr}T08:30:00Z`,
      updatedAt: `${todayStr}T10:05:00Z`,
    },
    {
      id: 'apt-today-4',
      hospitalId: 'hosp-1',
      patientId: 'pat-103',
      patientName: 'Eleanor Vance',
      patientPhone: '+1 (555) 234-9871',
      patientAge: 62,
      patientGender: 'FEMALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '10:45',
      endTime: '11:00',
      status: 'CONFIRMED',
      reason: 'ECG abnormal rhythm investigation',
      tokenNumber: 'C-026',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 35,
      noShowRiskLevel: 'MEDIUM',
      estimatedWaitMinutes: 42,
      createdAt: `${todayStr}T08:45:00Z`,
      updatedAt: `${todayStr}T08:45:00Z`,
    },
    {
      id: 'apt-today-5',
      hospitalId: 'hosp-1',
      patientId: 'pat-104',
      patientName: 'Samuel Jackson',
      patientPhone: '+1 (555) 888-1212',
      patientAge: 51,
      patientGender: 'MALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '11:00',
      endTime: '11:15',
      status: 'CONFIRMED',
      reason: 'Shortness of breath upon mild exertion',
      tokenNumber: 'C-027',
      priority: 'NORMAL',
      bookingSource: 'AI_ASSISTANT',
      noShowRiskScore: 28,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 57,
      createdAt: `${todayStr}T09:00:00Z`,
      updatedAt: `${todayStr}T09:00:00Z`,
    },
    // Walk-in today for General Medicine
    {
      id: 'apt-today-6',
      hospitalId: 'hosp-1',
      patientId: 'pat-105',
      patientName: 'David Miller',
      patientPhone: '+1 (555) 777-6543',
      patientAge: 29,
      patientGender: 'MALE',
      doctorId: 'doc-7',
      doctorName: 'Dr. Rajiv Menon, MBBS, MD',
      departmentId: 'dept-6',
      departmentName: 'General Medicine',
      appointmentDate: todayStr,
      startTime: '10:15',
      endTime: '10:30',
      status: 'WAITING',
      reason: 'Acute fever (101°F) for 2 days with productive cough',
      tokenNumber: 'GM-014',
      priority: 'WALK_IN',
      bookingSource: 'WALK_IN',
      noShowRiskScore: 5,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 15,
      checkedInAt: `${todayStr}T10:00:00Z`,
      createdAt: `${todayStr}T10:00:00Z`,
      updatedAt: `${todayStr}T10:00:00Z`,
    },
    // Emergency priority patient for General Medicine
    {
      id: 'apt-today-7',
      hospitalId: 'hosp-1',
      patientId: 'pat-106',
      patientName: 'Sophia Turner',
      patientPhone: '+1 (555) 444-9900',
      patientAge: 41,
      patientGender: 'FEMALE',
      doctorId: 'doc-7',
      doctorName: 'Dr. Rajiv Menon, MBBS, MD',
      departmentId: 'dept-6',
      departmentName: 'General Medicine',
      appointmentDate: todayStr,
      startTime: '10:30',
      endTime: '10:45',
      status: 'IN_CONSULTATION',
      reason: 'Severe acute abdominal pain in right lower quadrant',
      tokenNumber: 'GM-015',
      priority: 'EMERGENCY',
      bookingSource: 'RECEPTION',
      noShowRiskScore: 0,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      checkedInAt: `${todayStr}T10:10:00Z`,
      consultationStartedAt: new Date(Date.now() - 5 * 60000).toISOString(),
      createdAt: `${todayStr}T10:10:00Z`,
      updatedAt: `${todayStr}T10:15:00Z`,
    },
    // Completed consultation earlier today with e-Prescription
    {
      id: 'apt-today-8',
      hospitalId: 'hosp-1',
      patientId: 'pat-107',
      patientName: 'Grace Hopper',
      patientPhone: '+1 (555) 321-4567',
      patientAge: 65,
      patientGender: 'FEMALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '09:30',
      endTime: '09:45',
      status: 'COMPLETED',
      reason: 'Annual coronary calcium scoring consultation',
      tokenNumber: 'C-021',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 8,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      checkedInAt: `${todayStr}T09:15:00Z`,
      consultationStartedAt: `${todayStr}T09:30:00Z`,
      completedAt: `${todayStr}T09:46:00Z`,
      consultation: {
        id: 'cons-1',
        appointmentId: 'apt-today-8',
        doctorId: 'doc-1',
        patientId: 'pat-107',
        chiefComplaint: 'Annual cardiac screening, mild intermittent dizziness on standing.',
        diagnosis: 'Stage 1 Essential Hypertension, Mild Orthostatic Hypotension.',
        clinicalNotes: 'BP sitting 134/86 mmHg, standing 118/74 mmHg. Heart sounds S1, S2 regular without murmurs. Resting ECG shows sinus rhythm, normal axis. Advised hydration, gradual postural changes, and low-sodium diet.',
        prescriptions: [
          {
            id: 'rx-1',
            medicine: 'Telmisartan Tablets',
            dosage: '40 mg',
            frequency: '1-0-0 (Once daily morning)',
            duration: '30 days',
            instructions: 'Take with or without food. Monitor home BP weekly.',
          },
          {
            id: 'rx-2',
            medicine: 'Atorvastatin Tablets',
            dosage: '10 mg',
            frequency: '0-0-1 (Once daily at bedtime)',
            duration: '30 days',
            instructions: 'For lipid optimization. Avoid grapefruit juice.',
          },
        ],
        followUpDate: inTwoDaysStr,
        completedAt: `${todayStr}T09:46:00Z`,
      },
      createdAt: `${todayStr}T08:00:00Z`,
      updatedAt: `${todayStr}T09:46:00Z`,
    },
    // Cancelled and Missed for stats
    {
      id: 'apt-today-9',
      hospitalId: 'hosp-1',
      patientId: 'pat-108',
      patientName: 'Lucas Bennett',
      patientPhone: '+1 (555) 654-7890',
      patientAge: 38,
      patientGender: 'MALE',
      doctorId: 'doc-1',
      doctorName: 'Dr. Priya Sharma, MD, FACC',
      departmentId: 'dept-1',
      departmentName: 'Cardiology',
      appointmentDate: todayStr,
      startTime: '09:45',
      endTime: '10:00',
      status: 'CANCELLED',
      reason: 'Chest discomfort and follow-up consultation',
      cancellationReason: 'Patient had travel conflict and rescheduled for next week.',
      cancelledAt: `${todayStr}T08:50:00Z`,
      tokenNumber: 'C-022',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 65,
      noShowRiskLevel: 'HIGH',
      estimatedWaitMinutes: 0,
      createdAt: `${todayStr}T08:00:00Z`,
      updatedAt: `${todayStr}T08:50:00Z`,
    },
    {
      id: 'apt-today-10',
      hospitalId: 'hosp-1',
      patientId: 'pat-109',
      patientName: 'Emma Watson',
      patientPhone: '+1 (555) 789-0123',
      patientAge: 44,
      patientGender: 'FEMALE',
      doctorId: 'doc-3',
      doctorName: 'Dr. Aris Thorne, MD, PhD',
      departmentId: 'dept-2',
      departmentName: 'Neurology',
      appointmentDate: todayStr,
      startTime: '09:30',
      endTime: '09:50',
      status: 'MISSED',
      reason: 'Chronic migraine and visual aura assessment',
      cancellationReason: 'Patient failed to appear after 3 announcement calls.',
      tokenNumber: 'NE-005',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 78,
      noShowRiskLevel: 'HIGH',
      estimatedWaitMinutes: 0,
      createdAt: `${todayStr}T08:00:00Z`,
      updatedAt: `${todayStr}T10:00:00Z`,
    },
    // Past appointments for Alex Morgan
    {
      id: 'apt-past-1',
      hospitalId: 'hosp-1',
      patientId: 'pat-1',
      patientName: 'Alex Morgan',
      patientPhone: '+1 (555) 742-9988',
      patientAge: 34,
      patientGender: 'FEMALE',
      doctorId: 'doc-6',
      doctorName: 'Dr. Camille Laurent, MD',
      departmentId: 'dept-5',
      departmentName: 'Dermatology',
      appointmentDate: yesterdayStr,
      startTime: '14:00',
      endTime: '14:15',
      status: 'COMPLETED',
      reason: 'Skin rash on forearm and allergic contact dermatitis',
      tokenNumber: 'DERM-008',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 10,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      checkedInAt: `${yesterdayStr}T13:45:00Z`,
      consultationStartedAt: `${yesterdayStr}T14:02:00Z`,
      completedAt: `${yesterdayStr}T14:18:00Z`,
      consultation: {
        id: 'cons-2',
        appointmentId: 'apt-past-1',
        doctorId: 'doc-6',
        patientId: 'pat-1',
        chiefComplaint: 'Erythematous pruritic plaque on right forearm for 10 days.',
        diagnosis: 'Contact Allergic Dermatitis, secondary to nickel exposure.',
        clinicalNotes: 'Mild scaling with clear borders. No signs of secondary bacterial infection. Advised barrier protection and topical anti-inflammatory therapy.',
        prescriptions: [
          {
            id: 'rx-3',
            medicine: 'Hydrocortisone 1% Cream',
            dosage: 'Topical application',
            frequency: 'Apply thin film twice daily',
            duration: '7 days',
            instructions: 'Wash hands before and after applying. Discontinue if burning sensation persists.',
          },
          {
            id: 'rx-4',
            medicine: 'Cetirizine 10 mg Tablets',
            dosage: '10 mg',
            frequency: '0-0-1 (Once at night)',
            duration: '5 days',
            instructions: 'For pruritus relief.',
          },
        ],
        completedAt: `${yesterdayStr}T14:18:00Z`,
      },
      createdAt: `${yesterdayStr}T10:00:00Z`,
      updatedAt: `${yesterdayStr}T14:18:00Z`,
    },
    // Future appointments
    {
      id: 'apt-fut-1',
      hospitalId: 'hosp-1',
      patientId: 'pat-1',
      patientName: 'Alex Morgan',
      patientPhone: '+1 (555) 742-9988',
      patientAge: 34,
      patientGender: 'FEMALE',
      doctorId: 'doc-3',
      doctorName: 'Dr. Aris Thorne, MD, PhD',
      departmentId: 'dept-2',
      departmentName: 'Neurology',
      appointmentDate: tomorrowStr,
      startTime: '11:00',
      endTime: '11:20',
      status: 'CONFIRMED',
      reason: 'Migraine frequency evaluation and prophylactic therapy options',
      tokenNumber: 'NE-012',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 15,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      meetLink: 'https://meet.google.com/med-flow-neuro',
    },
    {
      id: 'apt-fut-2',
      hospitalId: 'hosp-1',
      patientId: 'pat-110',
      patientName: 'Benjamin Davis',
      patientPhone: '+1 (555) 123-4567',
      patientAge: 53,
      patientGender: 'MALE',
      doctorId: 'doc-4',
      doctorName: 'Dr. Elena Rostova, MD',
      departmentId: 'dept-3',
      departmentName: 'Orthopedics',
      appointmentDate: tomorrowStr,
      startTime: '09:00',
      endTime: '09:15',
      status: 'CONFIRMED',
      reason: 'Chronic right knee osteoarthritis and steroid injection inquiry',
      tokenNumber: 'ORTH-003',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 22,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'apt-fut-3',
      hospitalId: 'hosp-1',
      patientId: 'pat-111',
      patientName: 'Hannah Abbott',
      patientPhone: '+1 (555) 678-9012',
      patientAge: 7,
      patientGender: 'FEMALE',
      doctorId: 'doc-5',
      doctorName: 'Dr. David Cho, MD, FAAP',
      departmentId: 'dept-4',
      departmentName: 'Pediatrics',
      appointmentDate: tomorrowStr,
      startTime: '10:00',
      endTime: '10:15',
      status: 'CONFIRMED',
      reason: 'Annual pediatric developmental wellness checkup and MMR booster',
      tokenNumber: 'PED-007',
      priority: 'NORMAL',
      bookingSource: 'ONLINE',
      noShowRiskScore: 14,
      noShowRiskLevel: 'LOW',
      estimatedWaitMinutes: 0,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  // Add more historical & today appointments for varied departments to achieve 40+ rich operational records
  const deptDocs = [
    { doc: 'doc-1', dept: 'dept-1', prefix: 'C', fee: 120, name: 'Dr. Priya Sharma, MD, FACC' },
    { doc: 'doc-2', dept: 'dept-1', prefix: 'C', fee: 130, name: 'Dr. Marcus Vance, MD' },
    { doc: 'doc-3', dept: 'dept-2', prefix: 'NE', fee: 150, name: 'Dr. Aris Thorne, MD, PhD' },
    { doc: 'doc-4', dept: 'dept-3', prefix: 'ORT', fee: 110, name: 'Dr. Elena Rostova, MD' },
    { doc: 'doc-5', dept: 'dept-4', prefix: 'PED', fee: 90, name: 'Dr. David Cho, MD, FAAP' },
    { doc: 'doc-6', dept: 'dept-5', prefix: 'DERM', fee: 100, name: 'Dr. Camille Laurent, MD' },
    { doc: 'doc-7', dept: 'dept-6', prefix: 'GM', fee: 80, name: 'Dr. Rajiv Menon, MBBS, MD' },
  ];

  const firstNames = ['Liam', 'Olivia', 'Noah', 'Emma', 'Oliver', 'Charlotte', 'Elijah', 'Amelia', 'James', 'Ava', 'William', 'Sophia', 'Henry', 'Isabella', 'Lucas', 'Mia', 'Benjamin', 'Evelyn', 'Theodore', 'Harper'];
  const lastNames = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin'];

  let count = 20;
  for (let d = 0; d < deptDocs.length; d++) {
    const item = deptDocs[d];
    for (let i = 1; i <= 4; i++) {
      count++;
      const pIdx = (d * 4 + i) % firstNames.length;
      const pName = `${firstNames[pIdx]} ${lastNames[pIdx]}`;
      const hour = 11 + Math.floor(i / 2);
      const min = (i % 2) * 30;
      const timeStr = `${hour.toString().padStart(2, '0')}:${min.toString().padStart(2, '0')}`;
      const endMin = min + 15;
      const endTimeStr = `${hour.toString().padStart(2, '0')}:${endMin.toString().padStart(2, '0')}`;

      appointments.push({
        id: `apt-gen-${count}`,
        hospitalId: 'hosp-1',
        patientId: `pat-auto-${count}`,
        patientName: pName,
        patientPhone: `+1 (555) ${100 + count}-${2000 + count}`,
        patientAge: 25 + (count % 50),
        patientGender: count % 2 === 0 ? 'MALE' : 'FEMALE',
        doctorId: item.doc,
        doctorName: item.name,
        departmentId: item.dept,
        departmentName: INITIAL_DEPARTMENTS.find((dp) => dp.id === item.dept)?.name || 'General OPD',
        appointmentDate: todayStr,
        startTime: timeStr,
        endTime: endTimeStr,
        status: i === 1 ? 'CHECKED_IN' : 'CONFIRMED',
        reason: 'General outpatient medical evaluation and symptom assessment',
        tokenNumber: `${item.prefix}-${(10 + i).toString().padStart(3, '0')}`,
        priority: i === 4 ? 'WALK_IN' : 'NORMAL',
        bookingSource: i === 4 ? 'WALK_IN' : 'ONLINE',
        noShowRiskScore: 10 + ((count * 7) % 50),
        noShowRiskLevel: count % 3 === 0 ? 'MEDIUM' : 'LOW',
        estimatedWaitMinutes: (i + 1) * 15,
        createdAt: `${todayStr}T08:00:00Z`,
        updatedAt: `${todayStr}T08:00:00Z`,
      });
    }
  }

  return appointments;
}
